# Source version of this workflow lives in https://github.com/slds-lmu/lecture_service/service/.github/workflows
# Please only update by copying from there to avoid divergences
on:
  # Allow manually trigegring the workflow via GitHub website, gh CLI tool etc.
  # Also adds parameter to enable tmate (inetractive tmux session for debugging)
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  # Run this workflow regularly just in case there are upstream changes that would be missed otherwise
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
    # See https://crontab.guru for a cron helper
    # * is a special character in YAML so you have to quote this string
    # - cron:  '30 6 * * *'
  push:
    # Activate on pushes to both the main or master branches (inconsistently used across lecture repos)
    branches: [main, master]

name: update-service-components

jobs:
  update-service-components:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # 0 indicates all history for all branches and tags, 1 is shallow (and default)
          fetch-depth: 1
          # Don't show progress bar, very verbose for large repos
          show-progress: false

      # Get a tmux ssh session for interactive debugging
      # Controlled via inputs from GitHub webinterface
      # See https://github.com/mxschmitt/action-tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      # curling the repository tarball which contains the whole repo in a subfolder slds-lmu-lecture_service-<SHA>
      # which requires to --strip-components=2 to get to the level of the ./service/ repo contents
      # and "./*/service" specifies to extract only this specific subfolder. The * is used to not
      # have to bother getting the exact file name of the root folder which would vary due to the SHA.
      - name: Get service components
        run: |
          curl -sL https://api.github.com/repos/slds-lmu/lecture_service/tarball/main | tar -xz --directory=./ --wildcards --strip-components=2 "*/service"

      # Use this pull request action to auto-generate a PR with the changes
      # See https://github.com/peter-evans/create-pull-request#action-inputs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
      # Note: This workflow might update workflow files in .github/workflows, which is not allowed by default
      #   and as such we need to manually create a PAT with the workflow permission and repo scope and add it
      #   via the GitHub settings for each lecture repository.
      # These tokens expire after a maximum of 1 year so this is unfortunate.
      # See https://github.com/settings/tokens?type=beta
          token: ${{ secrets.CUSTOM_PAT }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          title: "[Automated] Update service components"
          commit-message: "Update service components"
          body: |
              Automated changes by `update-service-components.yaml` workflow.
              Compare and merge to keep common assets up to date with [lecture_service/service](slds-lmu/lecture_service).
              This branch will automatically be updated on subsequent commits.

              Files that are kept track of include:
              - The `style` folder for LaTeX style files and preambles.
              - Makefiles in `slides/`, specifically `tex.mk` and `R.mk`.
              - GitHub actions workflows in `.github`.
              - LICENSE and other common assets that do not need to differ between lectures.
              - .gitattributes and .editorconfig, in an attempt to prevent common minor issues.
          branch: update-service-components
          add-paths: .
